from typing import Final


STEP_FIELDS: Final[tuple[str, ...]] = (
    "step",
    "position_x",
    "position_y",
    "energy",
    "health",
    "curiosity",
    "reward",
    "predicted_reward",
    "loss",
    "event",
    "visited_count",
    "known_cell_count",
    "goal_kind",
    "goal_target_x",
    "goal_target_y",
    "memory_goal_age",
    "memory_goal_switch_count",
    "memory_recent_revisit_count",
    "memory_stuck_counter",
    "memory_recent_rest_count",
    "memory_energy_trend",
    "memory_last_food_x",
    "memory_last_food_y",
    "memory_last_mystery_x",
    "memory_last_mystery_y",
    "memory_last_danger_x",
    "memory_last_danger_y",
    "coverage_total_world_cells",
    "coverage_seen_cell_count",
    "coverage_visited_cell_count",
    "coverage_unseen_cell_count",
    "coverage_seen_ratio",
    "coverage_visited_ratio",
    "coverage_frontier_count",
    "coverage_newly_seen_count",
    "coverage_newly_visited_count",
    "coverage_first_full_seen_step",
    "coverage_first_full_visited_step",
    "rule_action",
    "action_reason",
    "network_action",
    "choices_agree",
    "imagination_action",
    "imagination_expected_reward",
    "imagination_utility",
    "rule_imagined_reward",
    "rule_imagined_utility",
    "imagination_agrees",
    "termination_reason",
)

OUTCOME_FIELDS: Final[tuple[str, ...]] = (
    "outcome_predicted_energy_change",
    "outcome_actual_energy_change",
    "outcome_predicted_health_change",
    "outcome_actual_health_change",
    "outcome_predicted_curiosity_change",
    "outcome_actual_curiosity_change",
    "outcome_predicted_event",
    "outcome_actual_event",
    "outcome_event_correct",
    "outcome_state_mae",
    "outcome_reset_state_mae",
    "outcome_persistent_better_than_reset",
    "outcome_total_loss",
    "outcome_state_loss",
    "outcome_event_loss",
    "outcome_neural_state_mean",
    "outcome_neural_state_std",
    "outcome_neural_state_min",
    "outcome_neural_state_max",
)

STEP_CSV_FIELDNAMES: Final[tuple[str, ...]] = (
    STEP_FIELDS + OUTCOME_FIELDS
)
